# Kapsel Configuration
#
# Configuration is loaded in priority order:
# 1. Environment variables (highest priority)
# 2. This file (config.toml)
# 3. Built-in defaults (lowest priority)
#
# Any setting can be overridden with environment variables. For example:
#   database_url = "..." in this file
#   DATABASE_URL="..." as environment variable (takes precedence)
#
# To use environment variables, convert setting names to SCREAMING_SNAKE_CASE:
#   database_max_connections → DATABASE_MAX_CONNECTIONS
#   worker_pool_size → WORKER_POOL_SIZE
#   retry_base_delay_ms → RETRY_BASE_DELAY_MS
#
# The service works out-of-the-box with sensible defaults. You only need to
# configure what differs from defaults for your environment.

# ============================================================================
# Database Configuration
# ============================================================================

# PostgreSQL connection string
# Default: "postgresql://localhost/kapsel"
database_url = "postgresql://postgres:password@localhost:5432/kapsel"

# Maximum number of connections in the pool
# Default: 10
database_max_connections = 20

# Minimum number of connections to maintain
# Default: 2
database_min_connections = 5

# Connection acquire timeout in seconds
# Default: 10
database_connection_timeout = 15

# Connection idle timeout in seconds (10 minutes)
# Default: 600
database_idle_timeout = 600

# Maximum connection lifetime in seconds (30 minutes)
# Default: 1800
database_max_lifetime = 1800

# ============================================================================
# HTTP Server Configuration
# ============================================================================

# Server bind address
# Default: "127.0.0.1"
host = "0.0.0.0"

# Server bind port
# Default: 8080
port = 8080

# HTTP request timeout in seconds
# Default: 30
request_timeout = 60

# ============================================================================
# Webhook Delivery Configuration
# ============================================================================

# Number of concurrent delivery workers
# Default: 4
worker_pool_size = 8

# Maximum events to claim per worker batch
# Default: 10
worker_queue_size = 25

# ============================================================================
# Retry Configuration
# ============================================================================

# Maximum retry attempts per webhook
# Default: 5
max_retry_attempts = 10

# Base delay for exponential backoff in milliseconds
# Default: 1000 (1 second)
retry_base_delay_ms = 2000

# Maximum delay between retries in milliseconds
# Default: 60000 (1 minute)
retry_max_delay_ms = 300000

# Jitter factor for retry timing (0.0 to 1.0)
# Default: 0.1
retry_jitter_factor = 0.15

# ============================================================================
# Circuit Breaker Configuration
# ============================================================================

# Number of failures to trigger circuit breaker open state
# Default: 5
circuit_breaker_failure_threshold = 10

# Number of successes to close circuit breaker from half-open
# Default: 2
circuit_breaker_success_threshold = 3

# Time in seconds to wait before transitioning from open to half-open
# Default: 30
circuit_breaker_timeout_seconds = 60

# ============================================================================
# HTTP Client Configuration
# ============================================================================

# HTTP request timeout for webhook delivery in seconds
# Default: 30
delivery_timeout_seconds = 45

# ============================================================================
# Attestation Configuration
# ============================================================================

# Batch size for processing attestation events
# Default: 100
attestation_batch_size = 200

# ============================================================================
# Logging Configuration
# ============================================================================

# Log level configuration
# Options: "error", "warn", "info", "debug", "trace"
# Default: "info"
rust_log = "info,kapsel=debug"

# Example environment-specific configurations:
#
# Development:
# rust_log = "debug,kapsel=trace,sqlx=debug"
# database_max_connections = 5
# worker_pool_size = 2
#
# Production:
# rust_log = "warn,kapsel=info"
# database_max_connections = 50
# worker_pool_size = 16
# max_retry_attempts = 15
